
package cl.bice.ws.servicio;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CrearDesafioWSService", targetNamespace = "http://servicio.ws.bice.cl/", wsdlLocation = "http://soades.bice.local:7001/Internet/SFA/CrearDesafioWS?wsdl")
public class CrearDesafioWSService
    extends Service
{

    private final static URL CREARDESAFIOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREARDESAFIOWSSERVICE_EXCEPTION;
    private final static QName CREARDESAFIOWSSERVICE_QNAME = new QName("http://servicio.ws.bice.cl/", "CrearDesafioWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://soades.bice.local:7001/Internet/SFA/CrearDesafioWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREARDESAFIOWSSERVICE_WSDL_LOCATION = url;
        CREARDESAFIOWSSERVICE_EXCEPTION = e;
    }

    public CrearDesafioWSService() {
        super(__getWsdlLocation(), CREARDESAFIOWSSERVICE_QNAME);
    }

    public CrearDesafioWSService(String url){
        super(getURLFromSource(url), CREARDESAFIOWSSERVICE_QNAME);
    }

    private static URL getURLFromSource(String url){
        URL u = null;
        WebServiceException e = null;
        try{
            u = new URL(url);
        }
        catch(MalformedURLException ex){
            e = new WebServiceException(ex);
        }
        return u;
    }

    public CrearDesafioWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREARDESAFIOWSSERVICE_QNAME, features);
    }

    public CrearDesafioWSService(URL wsdlLocation) {
        super(wsdlLocation, CREARDESAFIOWSSERVICE_QNAME);
    }

    public CrearDesafioWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREARDESAFIOWSSERVICE_QNAME, features);
    }

    public CrearDesafioWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrearDesafioWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CrearDesafioWS
     */
    @WebEndpoint(name = "CrearDesafioWSPort")
    public CrearDesafioWS getCrearDesafioWSPort() {
        return super.getPort(new QName("http://servicio.ws.bice.cl/", "CrearDesafioWSPort"), CrearDesafioWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrearDesafioWS
     */
    @WebEndpoint(name = "CrearDesafioWSPort")
    public CrearDesafioWS getCrearDesafioWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.ws.bice.cl/", "CrearDesafioWSPort"), CrearDesafioWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREARDESAFIOWSSERVICE_EXCEPTION!= null) {
            throw CREARDESAFIOWSSERVICE_EXCEPTION;
        }
        return CREARDESAFIOWSSERVICE_WSDL_LOCATION;
    }

}
