
package cl.bice.ws.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CrearDesafioWS", targetNamespace = "http://servicio.ws.bice.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrearDesafioWS {


    /**
     * 
     * @param tipoCliente
     * @param mensajeDesafio
     * @param estado
     * @param tipoDesafio
     * @param mensajeUsuario
     * @param canalOrigen
     * @param desafios
     * @param usuarioId
     * @param ipCliente
     */
    @WebMethod(operationName = "CrearDesafio")
    @RequestWrapper(localName = "CrearDesafio", targetNamespace = "http://servicio.ws.bice.cl/", className = "cl.bice.ws.servicio.CrearDesafio")
    @ResponseWrapper(localName = "CrearDesafioResponse", targetNamespace = "http://servicio.ws.bice.cl/", className = "cl.bice.ws.servicio.CrearDesafioResponse")
    public void crearDesafio(
            @WebParam(name = "UsuarioId", targetNamespace = "")
            String usuarioId,
            @WebParam(name = "CanalOrigen", targetNamespace = "")
            String canalOrigen,
            @WebParam(name = "TipoCliente", targetNamespace = "")
            String tipoCliente,
            @WebParam(name = "IPCliente", targetNamespace = "")
            String ipCliente,
            @WebParam(name = "TipoDesafio", targetNamespace = "")
            String tipoDesafio,
            @WebParam(name = "MensajeUsuario", targetNamespace = "")
            String mensajeUsuario,
            @WebParam(name = "MensajeDesafio", targetNamespace = "")
            MensajeDesafioType mensajeDesafio,
            @WebParam(name = "Estado", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<EstadoType> estado,
            @WebParam(name = "Desafios", targetNamespace = "", mode = WebParam.Mode.OUT)
            Holder<DesafiosType> desafios);

}
