
package cl.bice.ws.servicio;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListarDesafiosWSService", targetNamespace = "http://servicio.ws.bice.cl/", wsdlLocation = "http://soades.bice.local:7001/Internet/SFA/ListarDesafiosWS?wsdl")
public class ListarDesafiosWSService
    extends Service
{

    private final static URL LISTARDESAFIOSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTARDESAFIOSWSSERVICE_EXCEPTION;
    private final static QName LISTARDESAFIOSWSSERVICE_QNAME = new QName("http://servicio.ws.bice.cl/", "ListarDesafiosWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://soades.bice.local:7001/Internet/SFA/ListarDesafiosWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTARDESAFIOSWSSERVICE_WSDL_LOCATION = url;
        LISTARDESAFIOSWSSERVICE_EXCEPTION = e;
    }

    public ListarDesafiosWSService() {
        super(__getWsdlLocation(), LISTARDESAFIOSWSSERVICE_QNAME);
    }

    public ListarDesafiosWSService(String url){
        super(getURLFromSource(url), LISTARDESAFIOSWSSERVICE_QNAME);
    }

    private static URL getURLFromSource(String url){
        URL u = null;
        WebServiceException e = null;
        try{
            u = new URL(url);
        }
        catch(MalformedURLException ex){
            e = new WebServiceException(ex);
        }
        return u;
    }

    public ListarDesafiosWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTARDESAFIOSWSSERVICE_QNAME, features);
    }

    public ListarDesafiosWSService(URL wsdlLocation) {
        super(wsdlLocation, LISTARDESAFIOSWSSERVICE_QNAME);
    }

    public ListarDesafiosWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTARDESAFIOSWSSERVICE_QNAME, features);
    }

    public ListarDesafiosWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListarDesafiosWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListarDesafiosWS
     */
    @WebEndpoint(name = "ListarDesafiosWSPort")
    public ListarDesafiosWS getListarDesafiosWSPort() {
        return super.getPort(new QName("http://servicio.ws.bice.cl/", "ListarDesafiosWSPort"), ListarDesafiosWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListarDesafiosWS
     */
    @WebEndpoint(name = "ListarDesafiosWSPort")
    public ListarDesafiosWS getListarDesafiosWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.ws.bice.cl/", "ListarDesafiosWSPort"), ListarDesafiosWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTARDESAFIOSWSSERVICE_EXCEPTION!= null) {
            throw LISTARDESAFIOSWSSERVICE_EXCEPTION;
        }
        return LISTARDESAFIOSWSSERVICE_WSDL_LOCATION;
    }

}
